USE DATABASE {DATABASE_NAME};

-- Create schemas
CREATE SCHEMA IF NOT EXISTS BRONZE COMMENT = 'Raw data layer';
CREATE SCHEMA IF NOT EXISTS SILVER COMMENT = 'Cleansed data layer';
CREATE SCHEMA IF NOT EXISTS GOLD COMMENT = 'Business logic layer';
CREATE SCHEMA IF NOT EXISTS CORTEX COMMENT = 'AI/ML models and features';
CREATE SCHEMA IF NOT EXISTS AUDIT COMMENT = 'Audit and logging';
