USE DATABASE {DATABASE_NAME};

-- Bronze layer tables
CREATE OR REPLACE TABLE BRONZE.CUSTOMER (
    CUSTOMER_ID NUMBER(38,0) NOT NULL,
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    EMAIL VARCHAR(100) NOT NULL,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_CUSTOMER PRIMARY KEY (CUSTOMER_ID)
);

-- Audit table
CREATE OR REPLACE TABLE AUDIT.PROCESS_LOGS (
    LOG_ID NUMBER(38,0) AUTOINCREMENT,
    PROCESS_NAME VARCHAR(200),
    START_TIME TIMESTAMP_NTZ,
    END_TIME TIMESTAMP_NTZ,
    STATUS VARCHAR(20),
    ERROR_MESSAGE VARCHAR(5000),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
